spring:
    freemarker:
        enabled: false
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    second-datasource:
        url: 10.10.25.157
        port: 5432
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
            path: /h2            
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
server:
    port: 2222
