spring:
    freemarker:
        enabled: false
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
    datasource:
        url : jdbc:postgresql://localhost:5432/postgres?currentSchema=jose
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: pg5465
    second-datasource:
        jdbcUrl : jdbc:postgresql://10.10.25.157:5432/postgres?currentSchema=jose
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres        
    third-datasource:    
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
            jdbc:
                lob:
                    non_contextual_creation: true
    backupjpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
            path: /h2            
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
server:
    port: 2222
